server:
  port: 80

spring:
  application:
    name: cloud-consumer-order-feign

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
    fetch-registry: true

feign:
  hystrix:
    enabled: true